production:
  cloud_name: hhczqqtgs
  api_key: "971335813656987"
  api_secret: bPuirir7FQQE_EMZkoH4DLZh1j0

development:
  cloud_name: hhczqqtgs
  api_key: "971335813656987"
  api_secret: bPuirir7FQQE_EMZkoH4DLZh1j0
