# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# @import_img = (i) ->
#   document.getElementByclass("mem-pic").src = "mem_"+i


# glyphicon set to each button
# member pageを読み込んだとき一瞬2個のgyphiconがでる

$ ->
  i = 0
  while i < 3
    span = document.createElement('span')
    btn = document.getElementById('btn-' + i)
    if i == 0
      span.setAttribute 'class', 'glyphicon glyphicon-pencil'
    else if i == 1
      span.setAttribute 'class', 'glyphicon glyphicon-book'
    else
      span.setAttribute 'class', 'glyphicon glyphicon-user'
    if btn != null
      btn.appendChild span
    i++
  return

# ---
# generated by js2coffee 2.2.0
